### ISSUE TITLE
Type or namespace 'NUnit' could not be found

### ISSUE THREAD

**Issue by killazys** [thefuntastic/Unity3d-Finite-State-Machine#10]
This error occurs for all three scripts in the Test folder.

The folder structure is obviously okay (in Editor).

My installation directory is in a different drive from where the directory of my clone is. Does that affect it?

**Comment by thefuntastic** [comment]
Hi, as mentioned in the Read me these are dependencies on external libraries I thought it best to not include here:

>Dependencies
There are no dependencies, but if you're working with the source files, the tests rely on the UnityTestTools package which can be downloaded from the Asset Store. These are non-essential, only work in the editor, and can be deleted if you so choose.
