### ISSUE TITLE
Time.timeScale > than certain value causes missing state changes

### ISSUE THREAD

**Issue by tosiabunio** [thefuntastic/Unity3d-Finite-State-Machine#11]
I'm using Time.timeScale to speed up level startup (hidden from the view). I noticed that some states for my objects are missed if the scale is above certain value (at least 5.0f). I noticed this in my complex code so I'm not sure if this can be reproduced with something simpler.

**Comment by thefuntastic** [comment]
Thanks for reporting and sorry for taking so long to get back to you (been crunching hard on Cadence). There will be an update coming soon that make the transition logic more stable. I'd like to ask that you try that first and see if that solves the problem. 

If the problem persists, I'll have to try create a test case that emulates the behaviour and then we can go from there. ;)

**Comment by thefuntastic** [comment]
Sorry, again this took longer than I expect. (Famous programmer optimism). A new version is up - if you haven't found a work around by now I'd appreciate if you could test the changes. 

(Note the is a breaking change as detailed in the Readme)

**Comment by tosiabunio** [comment]
I will test the new version immediately. Thanks!

**Comment by tosiabunio** [comment]
Well, there seems to be some issues with that I can't explain. I need to contact you directly in order to send you my project for further investigation. It's likely that other elements can be blamed for strange behavior but it's too difficult for me to find out who's to blame.

**Comment by thefuntastic** [comment]
Okay, you can send a zip to peter [at] madewithmonsterlove.com

**Comment by thefuntastic** [comment]
These issues should now be resolved that non IEnumerator Enter and Exit functions no longer use coroutines for transitions
