### ISSUE TITLE
Support multiple state machines on a single object.

### ISSUE THREAD

**Issue by thefuntastic** [thefuntastic/Unity3d-Finite-State-Machine#13]
Not being able to run two state machines is a serious limitation on separation of concerns. StateMachine script needs to be refactored in order to be able to allow multiple instances of State Behaviour to run concurrently without affecting each other.

**Comment by AAverin** [comment]
Are there plans to implement this feature?

**Comment by thefuntastic** [comment]
Yes there is, but there is no timeline for when. I'm simply too spread out on my own projects at the moment to commit to anything. :/

**Comment by AAverin** [comment]
I kinda re-worked your state machine a little bit - removed MonoBehaviour from StateEngine and re-written StateBehaviour to inherit from Monobehaviour and have a list of StateEngine implementations that would be executed for events like Update/FixedUpdate and others.

I'm not sure if this really worths a pull request, but so far I think I can use this new approach

**Comment by thefuntastic** [comment]
This is now supported as of V3.0
