### ISSUE TITLE
Anonymous Methods generate Warnings

### ISSUE THREAD

**Issue by nkoufou** [thefuntastic/Unity3d-Finite-State-Machine#14]
A warning is logged when anonymous methods are encountered. 
Added the following to skip those in StateEngine.Initialize in the loop that binds states to methods: 

if (methods[i].GetCustomAttributes(typeof(CompilerGeneratedAttribute), true).Length!=0)
	continue;

Might be a better way to filter these out when calling GetMethod above.

**Comment by thefuntastic** [comment]
Okay, thanks for reporting. I'll look at when I eventually get out of my crunch release cycle on Cadence and can pay the state machine some love an attention

**Comment by nkoufou** [comment]
Cadence looks cool BTW, I was quite a big fan of Electroplankton on the DS so I am looking forward to getting my hands on this.

**Comment by thefuntastic** [comment]
This has been added in the latest commit. Thanks for the fix!
