### ISSUE TITLE
Error with lambda which modifies instance variable

### ISSUE THREAD

**Issue by arganoid** [thefuntastic/Unity3d-Finite-State-Machine#16]
Method with name <ChooseCountry_Enter>m__80 could not resolve a matching state. Check method spelling

I get the error above with the following code (where 'ChooseCountry' is one of the states):
```
string chosenCountry;
void ChooseCountry_Enter()
{
	System.Action<string> onChosen = (chosen) => { chosenCountry = chosen; };
}
```
If I breakpoint Initialize in StateEngine, I see that all entries in 'methods' display as expected, except for:
`[9] = "Void <ChooseCountry_Enter>m__80(System.String)"`

The workaround is to make chosenCountry static.

**Comment by arganoid** [comment]
I just found that I get the same error if I try to call a non-static method in the lambda function

**Comment by thefuntastic** [comment]
Thanks for reporting. 

I have just pushed a fix that should resolve this.
