### ISSUE TITLE
[Suggestion] About state callbacks naming convention

### ISSUE THREAD

**Issue by minhdu** [thefuntastic/Unity3d-Finite-State-Machine#17]
I suggest support for better naming convention for state callbacks such as:
On[StateName]Enter, On[StateName]Exit, ...

Because of i think underscore not good for method name.
What i mean as mention in code below (not tested), please review:

**Before**
```
				var names = methods[i].Name.Split(separator);

				//Ignore functions without an underscore
				if (names.Length <= 1)
				{
					continue;
				}

				Enum key;
				try
				{
					key = (Enum) Enum.Parse(typeof(T), names[0]);
				}
				catch (ArgumentException)
				{
					//Not an method as listed in the state enum
					continue;
				}
```

**After**

```
				if(!methods[i].Name.Contains("On"))
					continue;

				string stateName = "";
				Enum stateEnum = (Enum)values.GetValue(0);
				for(int j=0; j<values.Length; j++) {
					if(methods[i].Name.Contains(values.GetValue(j).ToString())) {
						stateName = values.GetValue(j).ToString();
						stateEnum = (Enum)values.GetValue(j);
						break;
					}
				}

				if(string.IsNullOrEmpty(stateName))
					continue;

				string[] eventName = Regex.Split(methods[i].Name, stateName);
				var targetState = stateLookup[stateEnum];`

**Comment by thefuntastic** [comment]
Thank you for your suggestion, and contribution to this project! I agree that your suggestion is closer to C# naming conventions, however there are a few reasons for the current naming stlye:

- Underscores give you a clear hint that there is some kind of "Magic" happening.
- In a case with many helper methods it's very easy to, at a glance, differentiate state machine methods versus normal class methods;
- Without the underscore it becomes slightly awkward when combined with event handler conventions - `StateName_OnCollisionEnter` vs `OnStateNameOnCollisionEnter` 

Ultimately this is a matter of style and opinion. As such I'm happy the current convention is well suited to its function, and therefore I see no reason to incur the cost of making breaking changes for the sake of a style optimization. ;)
