### ISSUE TITLE
`UnityTest' could not be found. When run example project.

### ISSUE THREAD

**Issue by tim-hub** [thefuntastic/Unity3d-Finite-State-Machine#18]
And show this.

`Assets/Editor/MonsterLove/Tests/StateMachine/TestStateEngineInitialization.cs(7,7): error CS0246: The type or namespace name `UnityTest' could not be found. Are you missing a using directive or an assembly reference?`

**Comment by thefuntastic** [comment]
Hi Tim, grab the Unity Test Tools from the asset store, and this should resolve the issue. 

Ideally there should be a better way to manage dependencies, but for now this is a workable solution. Let me know if you have any more issues with the version of the Test Tools that the asset store provides.

**Comment by tim-hub** [comment]
where it the link? I did not find it.

**Comment by thefuntastic** [comment]
https://www.assetstore.unity3d.com/en/#!/content/13802
