### ISSUE TITLE
Changing state during update causes next state to double fire

### ISSUE THREAD

**Issue by thefuntastic** [thefuntastic/Unity3d-Finite-State-Machine#2]
This is because update fires before coroutines are updated, which is used to enter the state. 

Current work around, use lateupdate instead.

Ultimately need to make some design decisions around if Update can run while an enter coroutine is active. Start() in unity doesn't block Update? So maybe we just need a flag we can check to see if there are coroutines running.

**Comment by tosiabunio** [comment]
Lost whole day today trying to figure out what's wrong with my code. Thanks for the info. Great piece of code, anyway!

**Comment by thefuntastic** [comment]
This is now fix, in that changing state during StateName_Update() and StateName_LateUpdate() will no longer cause this behaviour. 

However this is still possible to cause similar issues when the state change is effected from outside the StateMachine convention, as described here:
https://github.com/thefuntastic/Unity3d-Finite-State-Machine/issues/5
