### ISSUE TITLE
Use in Unity5.5 error

### ISSUE THREAD

**Issue by ShenJinchang** [thefuntastic/Unity3d-Finite-State-Machine#22]
UNetWeaver error: Exception :System.MissingMethodException: Method not found: 'Mono.Cecil.ModuleDefinition.ImportReference'.
  at Unity.UNetWeaver.Weaver.Weave (System.String assName, IEnumerable`1 dependencies, IAssemblyResolver assemblyResolver, System.String unityEngineDLLPath, System.String unityUNetDLLPath, System.String outputDir) [0x0004b] in C:\buildslave\unity\build\Extensions\Networking\Weaver\UNetWeaver.cs:1713 
  at Unity.UNetWeaver.Weaver.WeaveAssemblies (IEnumerable`1 assemblies, IEnumerable`1 dependencies, IAssemblyResolver assemblyResolver, System.String outputDir, System.String unityEngineDLLPath, System.String unityUNetDLLPath) [0x0006e] in C:\buildslave\unity\build\Extensions\Networking\Weaver\UNetWeaver.cs:1837 
UnityEngine.Debug:LogError(Object)
Unity.UNetWeaver.Log:Error(String) (at C:/buildslave/unity/build/Extensions/Networking/Weaver/Program.cs:20)
Unity.UNetWeaver.Weaver:WeaveAssemblies(IEnumerable`1, IEnumerable`1, IAssemblyResolver, String, String, String) (at C:/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1844)
Unity.UNetWeaver.Program:Process(String, String, String, String[], String[], IAssemblyResolver, Action`1, Action`1) (at C:/buildslave/unity/build/Extensions/Networking/Weaver/Program.cs:34)
UnityEditor.Scripting.Serialization.Weaver:WeaveUnetFromEditor(String, String, String, String, Boolean)
............................
Failure generating network code.
UnityEditor.Scripting.Serialization.Weaver:WeaveUnetFromEditor(String, String, String, String, Boolean)
..........................
I use this case in Untiy 5.5,Prompt the error.

**Comment by thefuntastic** [comment]
Seems this is an error with Unity Test Tools and Unity 5.5:
https://issuetracker.unity3d.com/issues/unetweaver-error-after-upgrading-project-from-5-dot-4-to-5-dot-5-slash-5-dot-6

As a temporary solution you can delete the test tools or upgrade them. The test tools are not essential to the functioning of the state machine. 
https://forum.unity3d.com/threads/unetweaver-error-method-not-found-mono-cecil-moduledefinition-importreference.429397/

**Comment by ShenJinchang** [comment]
Thank you. I finish this problem. 
Using the latest Mono.Cecil.dll  replace the previous version.
Assets/UnityTestTools/IntegrationTestsFramework/Libs/Mono.Cecil.dll (Location of the symbol related to previous error)
C:/Program Files/Unity 5.5.0b2/Editor/Data/Managed/Mono.Cecil.dll (Location of the symbol related to previous error)

**Comment by thefuntastic** [comment]
Unity test tools has been removed from the project, also Unity 5.5 was a long time ago... 😅
