### ISSUE TITLE
ChangeState: Restart state not supported?

### ISSUE THREAD

**Issue by real-marco-b** [thefuntastic/Unity3d-Finite-State-Machine#24]
If I read the source correct, it is forbidden to pass the current state as new state parameter to the ChangeState method:

`if (currentState == nextState) return;`

Any reasons for that?
I have some kind of waypoint system an actor is patrolling.
Within the respective _Enter method I initialize movement, within the respective _Exit method I choose the next waypoint.
So proceed to the next waypoint could be an elegant ChangeState() call, passing the current state again, resulting in calling Enter->Update->Exit chain again.

Any reasons you're not supporting this?

Thank you.

**Comment by thefuntastic** [comment]
Sorry realised I never replied to this. Normally I try respond promptly. 

To the reason that was there was a naive assumption about optimisation (say if ChangeState was being called every frame). But of course in some situations this is not what you want to do. I actually have a modified version that allows you to configure this behaviour, but I haven't gotten round to testing it and checking it in. For the time being if anyone else needs a workaround, taking out that check *shouldn't* break anything.

**Comment by thefuntastic** [comment]
The `reenter` flag now exists to allow transitions back into the same state
