### ISSUE TITLE
WaitForSeconds in FSM freezing when calling method in child GameObject.

### ISSUE THREAD

**Issue by HHammerite** [thefuntastic/Unity3d-Finite-State-Machine#25]
The title pretty much explains what's happening. I have a FSM on a parent GameObject which has a WaitForSeconds in the _Enter method. This WaitForSeconds is freezing whenever I call any method on any script attached to child GameObjects. After un-parenting the child GameObjects which have the scripts on them it doesn't freeze. I'm guessing this isn't normal behavior?

**Comment by thefuntastic** [comment]
I see you closed the issue, did you find a resolution? For anyone else reading the parent object needs to be active in order for co-routines to run, just like any other unity game object
