### ISSUE TITLE
An assembly `Mono.Cecil' with the same identity has already been imported when opening example project in Unity 5.6.2f1

### ISSUE THREAD

**Issue by MeltdownInteractive** [thefuntastic/Unity3d-Finite-State-Machine#27]
As soon as I open the example project, I get this error...

error CS1703: An assembly `Mono.Cecil' with the same identity has already been imported. Consider removing one of the references
Assets/UnityTestTools/IntegrationTestsFramework/Libs/Mono.Cecil.dll (Location of the symbol related to previous error)
C:/Program Files/Unity 5.6.2f1/Editor/Data/Managed/Mono.Cecil.dll (Location of the symbol related to previous error)

If I remove that file, then I get even more errors.

**Comment by thefuntastic** [comment]
Unity 5.6 was long time ago. Closing this ticket :)
