### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by NeithWZ** [thefuntastic/Unity3d-Finite-State-Machine#28]
It seems that when the "methods" variable gets set in the public StateMachine const, it only grabs the methods for the top-level class.  I have a class that inherits from another that actually contains the callbacks for the FSM.  However, the inheriting class's methods get set, not the actual ".Initialize(this)" class.

I see removing the BindingFlags.DeclaredOnly flag will fix this, but is there a better way?

**Comment by zulfajuniadi** [comment]
Bump

**Comment by gazugafan** [comment]
Double bump

**Comment by cckelly** [comment]
That's what I ended up doing, the library should provide a way to say "I want inherited classes" in my opinion

**Comment by oriolmanya** [comment]
Solution of @NeithWZ worked for me as well

**Comment by thefuntastic** [comment]
BindingFlags.DeclaredOnly has been removed in the `v4.0` release
