### ISSUE TITLE
LastState property 

### ISSUE THREAD

**Issue by klinakuf** [thefuntastic/Unity3d-Finite-State-Machine#29]
https://github.com/thefuntastic/Unity3d-Finite-State-Machine/blob/53a80d9bbc5353db534a8d9919ee7b74c33ca2ec/example_project/Assets/MonsterLove/StateMachine/StateMachine.cs#L350

This never evaluates to true, so always the next return line is executed, which produces undesirable behavior:

https://github.com/thefuntastic/Unity3d-Finite-State-Machine/blob/53a80d9bbc5353db534a8d9919ee7b74c33ca2ec/example_project/Assets/MonsterLove/StateMachine/StateMachine.cs#L352

The condition should check if the lastState.state is null:

`if (lastState.state == null) return default(T);`

**Comment by thefuntastic** [comment]
This is an old ticket, but the LastState field has been updated with enhanced test coverage. This should no longer be an issue
