### ISSUE TITLE
Licensing & Contributions

### ISSUE THREAD

**Issue by netlander** [thefuntastic/Unity3d-Finite-State-Machine#30]
This implementation barely scratches the surface of what an FSM is supposed to do. If you change your licensing more developers might be able to contribute.

**Comment by tosiabunio** [comment]
Well, this is a very good license, especially for those who want to use this code. As the functionality goes, it's quite fine at the level of complexity it has at the moment.

**Comment by thefuntastic** [comment]
@netlander The project is licensed under the MIT licence, chosen specifically for broad it's broad permissions and ability for use on commercial projects. In what do you find this licence restrictive? 

It is a design feature that the library should above all be easy to understand for the average user, while providing a base for advanced users to extend it to their own needs. What kind of functionality would you like to see?

**Comment by netlander** [comment]
@thefuntastic looking at the licence in the code (top comments) wasn't clear that it was an MIT license, since it is then that's great.

As far as features are concerned the FMS I was hoping to incorporate into my project would be simple and straight forward to use as yours is but would be a "water tight" implementation of an FSM which can scale without becoming a pain to maintain.

Was hoping for at least the following features:

(1) Transitions.
(2) Actions that would trigger the transitioning to a different state.
(3) Events (arguably something that can be weaved into the current implementation without too much effort).

Just saying the above almost as a wish list, I looked at other solutions be they are fully fledged node editors with Behaviour Trees and tons of bloat.

Cheers
