### ISSUE TITLE
`MonsterLove.StateMachine.StateMachine<T>.ignoredNames' is assigned but its value is never used

### ISSUE THREAD

**Issue by Obiwarn** [thefuntastic/Unity3d-Finite-State-Machine#32]
Can this line then be removed?

StateMachine/StateMachine.cs(60,29): warning CS0414: The private field `MonsterLove.StateMachine.StateMachine<T>.ignoredNames' is assigned but its value is never used

**Comment by thefuntastic** [comment]
Necropost! As of `v4.0` the ignored names concept no longer exists. ;)
