### ISSUE TITLE
windows store build errors

### ISSUE THREAD

**Issue by asoft2013** [thefuntastic/Unity3d-Finite-State-Machine#4]
Hi i've got an errors while build for Windows Store
Assets\MonsterLove\StateMachine\StateMachineEngine.cs(33,15): error CS1061: "System.Type" �� ᮤ�ন� ��।������ ��� "GetMethods". �� 㤠���� ����� ��⮤  �����७�� "GetMethods", �ਭ����騩 ������ ���㬥�� ⨯� "System.Type"  (�ய�饭� ��४⨢� using ��� ��뫪� �� ᡮ���?)

Assets\MonsterLove\StateMachine\StateMachineEngine.cs(100,24): error CS0117: "System.Delegate" �� ᮤ�ন� ��।������ ��� "CreateDelegate"

**Comment by layinka** [comment]
Hi,
Any fix for this yet?

**Comment by thefuntastic** [comment]
Unfortunately not. A combination of the fact I can't compile for windows store and the fact that I'm super deep in a crunch cycle means I won't be looking at this any time soon, if at all. I am however quite happy to accept a pull request if and window store devs wanna fix it? ;)

**Comment by anchpop** [comment]
Just chiming in to say that I took a crack at trying to port this to the Windows Store, but the it doesn't seem to support IConvertable. All these restrictions in WIndows RT are really annoying

**Comment by thefuntastic** [comment]
Windows store is likely to never be a compatible platform
