### ISSUE TITLE
UnityEngine.StateMachineBehaviour is now defined and in conflict

### ISSUE THREAD

**Issue by tosiabunio** [thefuntastic/Unity3d-Finite-State-Machine#9]
In Unity 5. Of course it may be resolved by refering MonsterLove.StateMachine.StateMachineBehaviour in class declaration.

**Comment by thefuntastic** [comment]
Ah bugger, thanks for reporting this. 

Can also be resolved by writing 
```using StateMachineBehaviour = MonsterLove.StateMachine.StateMachineBehaviour; ```
in your imports declaration, which saves you having to type it out each time. 

I'm on the road so it's going to be at least a few weeks before I get the chance to patch this

**Comment by thefuntastic** [comment]
Fixed in version 2.3
